# Use a base Python image
FROM python:3.9-slim
# FROM ros:humble

# Set the working directory in the container
# ARG FOLDER_NAME=dynamic-box
WORKDIR /app

RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libx11-dev \
    libxext6 \
    libxrender1 && \
    rm -rf /var/lib/apt/lists/*

# Library installations
RUN pip install --no-cache-dir matplotlib
RUN pip install --no-cache-dir matplotlib scipy

# Default command to run a script (optional)
CMD ["python"]
